# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zif8Mz5NTUcT0AxdTJLj0dF_9A450Cbs
"""

身高=float(input("請輸入您的身高(公尺):"))
體重=float(input("請輸入您的體重(公斤):"))

BMI=體重/(身高**2)

print(f"您的BMI是:{BMI:.2f}")